### ISSUE TITLE
"404: Not Found" for download links

### ISSUE THREAD

**Issue by ianbrandt** [codeclou/enterprise-integration-pattern-shapes-for-gliffy#7]
The current README.md references a [project page](https://codeclou.github.io/enterprise-integration-pattern-shapes-for-gliffy/).

The project page contains [Download .zip file](https://github.com/codeclou/enterprise-integration-pattern-shapes-for-gliffy/zipball/master) and [Download .tar.gz file](https://github.com/codeclou/enterprise-integration-pattern-shapes-for-gliffy/tarball/master) links, which after redirect lead to "404: Not Found" responses.

**Comment by clouless** [comment]
thanks for reporting. it is fixed now.

**Comment by ianbrandt** [comment]
Thanks for the speedy fix! Did you mean to drop the .tar.gz option?

**Comment by clouless** [comment]
yes the tar.gz was removed on purpose. We are redesigning the whole page anyway, and this was just a quick fix :)
